ClientSide/src/main/java/Client/ClientMain.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/examCreator.java
ClientSide/src/main/java/Client/principalDataController.java
ClientSide/src/main/java/Client/questionsEditor.java
ClientSide/src/main/java/Client/studentController.java
ClientSide/src/main/java/Client/teacherController.java
ClientSide/src/main/resources/Client/examCreator.fxml
ServerSide/src/main/resources/hibernate.properties

Now using Map instead of a List to keep Controllers
Keep the code much organize and simple

CLient better pasring of DataElement

---

Common/src/main/java/CloneEntities/AnsweredQuestion.java
Common/src/main/java/CloneEntities/CloneQuestion.java
Common/src/main/java/CloneEntities/CloneTest.java
ServerSide/src/main/java/Hibernate/Entities/Question.java
ServerSide/src/main/java/Hibernate/Entities/Test.java

Fix CloneTest and CloneQuestion C'tors

---

Common/src/main/java/CommonElements/DataElements.java
Common/src/main/java/CommonElements/EncryptionTool.java
ServerSide/src/main/java/Hibernate/Entities/User.java
ServerSide/src/main/java/Hibernate/HibernateMain.java
ServerSide/src/main/java/Server/SendEmail.java
ServerSide/src/main/java/Server/ServerMain.java
ServerSide/src/main/java/Server/ServerOperations.java

Enable user to login only once
Add to UserTable login flag. set the flag to "false" after logout

Add LogIn and LogOut opCodes (Common) and functions (Server)

---

ClientSide/src/main/java/Client/examCreator.java
ClientSide/src/main/resources/Client/principalController.fxml
ClientSide/src/main/resources/Client/studentController.fxml
ClientSide/src/main/resources/Client/teacherController.fxml

showing chosen question in generate test

A little commit of changing the main panel's tables

---

ServerSide/src/main/java/Hibernate/Entities/Course.java
ServerSide/src/main/java/Hibernate/Entities/Student.java
ServerSide/src/main/java/Server/ServerOperations.java

when adding exam it adds it to List<exams> in course class
when adding test it add StudentTest  to List<StudentTest> in Student who will be taking the test
added list<student> in course class
added list<course> in Student class

updated Serveroperation

---

Common/src/main/java/CloneEntities/CloneExam.java
ServerSide/src/main/java/Hibernate/Entities/Exam.java

In CloneExam removed points field and removed getters and setter because we added QuestionInExam instead, updated CreateClone to CLone List<QuestionInExam>.
In Exam changes List<question> to List<QuestionInExam>.

updated Exam and CloneExam

---

Common/src/main/java/CloneEntities/CloneExam.java
Common/src/main/java/CloneEntities/CloneTest.java
Common/src/main/java/UtilClasses/CloneQuestionInExam.java
Common/src/main/java/UtilClasses/DataElements.java
Common/src/main/java/UtilClasses/StudentExamCode.java
ServerSide/src/main/java/Hibernate/Entities/Exam.java
ServerSide/src/main/java/Hibernate/Entities/QuestionInExam.java
ServerSide/src/main/java/Hibernate/Entities/Test.java
ServerSide/src/main/java/Server/ServerMain.java
ServerSide/src/main/java/Server/ServerOperations.java

added CloneQiestionInExam  Class back
added List<CloneQuestion> in Exam
added List<StudentTest> in Test
added new studentExamCode Class

added GetStudentTestRelatedToStudentInExam and other updates

---

ClientSide/src/main/java/Client/AbstractController.java
ClientSide/src/main/java/Client/AbstractNavi.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/principalController.java
ClientSide/src/main/resources/Client/TestCodeInput.fxml
ClientSide/src/main/resources/Client/principalController.fxml
Common/src/main/java/CloneEntities/CloneTimeExtensionRequest.java

When a user logout the client sends opcode to server for recognizing it
Initial implement of requests table of principal

Logout Client + Requests Table

---

ClientSide/src/main/java/Client/AbstractController.java
ClientSide/src/main/java/Client/AbstractNavi.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/examCreator.java
ClientSide/src/main/java/Client/testGenerator.java
ClientSide/src/main/resources/Client/examCreator.fxml
Common/src/main/java/CloneEntities/CloneQuestion.java

Can now use an existing exam as a base to new exam
Background thread now stops when we swtich panel.

Exam creator update + Thread

---

ServerSide/src/main/java/Hibernate/Entities/StudentTest.java
ServerSide/src/main/java/Server/ServerOperations.java

now the grades updates based on correct answer

updated CheckAutomaticTest

---

Common/src/main/java/CloneEntities/CloneStudentTest.java
ServerSide/src/main/java/Hibernate/Entities/StudentTest.java
ServerSide/src/main/java/Server/ServerOperations.java

In handleStudentStartsTest if we have exception we send -1 back
In StudentTest added enum AttendanceStatus
In handleStudntFinshedTest added code to set Attendence in StudentTest to match CloneStudentTest

updated handleStudentStartsTest,  handleStudntFinshedTest and StudentTest

---

Common/src/main/java/UtilClasses/DataElements.java
ServerSide/src/main/java/Server/ServerMain.java
ServerSide/src/main/java/Server/ServerOperations.java

added opcode for updating grade of student after aproval of teacher
recieves List<ClonStudentTest>
return 1 if runs smoothly and -1 if we have an error

added TeacherUpdateGrade

---

ServerSide/src/main/java/Hibernate/Entities/Test.java
ServerSide/src/main/java/Hibernate/HibernateMain.java
ServerSide/src/main/java/Server/SendEmail.java
ServerSide/src/main/java/Server/ServerOperations.java

Dont work on master branch!!!!

Fix last Server commit

---

ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/autoTestController.java
ClientSide/src/main/java/Client/teacherController.java
Common/src/main/java/CloneEntities/CloneStudentTest.java
Common/src/main/java/CloneEntities/CloneTest.java
Common/src/main/java/CloneEntities/CloneTestStatistics.java
Common/src/main/java/CloneEntities/CloneUser.java
Common/src/main/java/UtilClasses/DataElements.java
ServerSide/src/main/java/Hibernate/Entities/Principal.java
ServerSide/src/main/java/Hibernate/Entities/Student.java
ServerSide/src/main/java/Hibernate/Entities/StudentTest.java
ServerSide/src/main/java/Hibernate/Entities/Teacher.java
ServerSide/src/main/java/Hibernate/Entities/Test.java
ServerSide/src/main/java/Hibernate/Entities/TestStatistics.java
ServerSide/src/main/java/Hibernate/Entities/User.java
ServerSide/src/main/java/Hibernate/HibernateMain.java
ServerSide/src/main/java/Server/ServerMain.java
ServerSide/src/main/java/Server/ServerOperations.java
ServerSide/src/main/java/Server/TimerHandler.java

Update StudentTest status after Test starts \ ends
Add CloneTestStatistics to CloneTest
Add identity number to User
Calculate Test grade AVG

Update Server according to recent requirements document

---

ClientSide/src/main/java/Client/AbstractController.java
ClientSide/src/main/java/Client/AbstractNavi.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/principalController.java
ClientSide/src/main/java/Client/studentController.java
ClientSide/src/main/java/Client/teacherController.java
ClientSide/src/main/resources/Client/principalController.fxml
ClientSide/src/main/resources/Client/studentController.fxml
ClientSide/src/main/resources/Client/teacherController.fxml
Common/src/main/java/CloneEntities/CloneStudentTest.java
Common/src/main/java/CloneEntities/CloneTimeExtensionRequest.java

Now most of table items are centered shown
Timer instead of Thread to refresh main tables
Tables now keep selection when updateing

Timer thread + Table upgrades

---

ClientSide/src/main/java/Client/AbstractController.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/autoTestController.java
ClientSide/src/main/java/Client/testEntracnce.java
ClientSide/src/main/resources/Client/autoTestController.fxml
ClientSide/src/main/resources/Client/studentController.fxml
Common/src/main/java/CloneEntities/CloneAnswerToQuestion.java
Common/src/main/java/CloneEntities/CloneStudentTest.java
ServerSide/src/main/java/Server/ServerOperations.java

Wait for Server to change status and then check Approve Grades of
teacher

Test process works

---

Common/src/main/java/UtilClasses/DataElements.java
ServerSide/src/main/java/Server/ServerMain.java
ServerSide/src/main/java/Server/ServerOperations.java

function receives ClonesQuestionTest  returns a list of CloneAnswerToQuestioin that are related to that student in CloneStudentTest

added SendAnswersToExamOfStudentTest

---

ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/personalInfo.java
ClientSide/src/main/java/Client/principalController.java
ClientSide/src/main/java/Client/requestController.java
ClientSide/src/main/java/Client/showStudentTest.java
ClientSide/src/main/java/Client/showStudentTests.java
ClientSide/src/main/java/Client/studentController.java
ClientSide/src/main/java/Client/teacherController.java
ClientSide/src/main/java/Client/testEntracnce.java
ClientSide/src/main/resources/Client/principalController.fxml
ClientSide/src/main/resources/Client/showStudentTest.fxml
ClientSide/src/main/resources/Client/showStudentTests.fxml
ClientSide/src/main/resources/Client/showTest.fxml
ClientSide/src/main/resources/Client/tableStyle.css
Common/src/main/java/CloneEntities/CloneStudentTest.java

Server needs to handle duplicates after student submit test
Server needs to handle Time Exten. Request- not working at the moment

Approve Grades works

---

ClientSide/src/main/java/Client/ClientMain.java
ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/autoTestController.java
ClientSide/src/main/java/Client/principalController.java
ClientSide/src/main/java/Client/requestController.java
ClientSide/src/main/java/Client/testEntracnce.java
Common/src/main/java/CloneEntities/CloneTimeExtensionRequest.java
ServerSide/src/main/java/Controllers/DoTestController.java
ServerSide/src/main/java/Hibernate/Entities/TimeExtensionRequest.java

Time Extension works

---

ClientSide/src/main/java/Client/AbstractController.java
ClientSide/src/main/java/Client/personalInfo.java
ClientSide/src/main/java/Client/testEntracnce.java
ClientSide/src/main/resources/Client/personalInfo.fxml

When a student exit the test though "X" in the window- the test goes to
WaitingForResult state
Personal Info edit option erased

Closing Test + Personal Info

---

ClientSide/src/main/java/Client/ClientService.java

Project is finished !

---

ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/autoTestController.java
ClientSide/src/main/java/Client/showStudentTest.java
ClientSide/src/main/java/Client/showStudentTests.java
ClientSide/src/main/java/Client/studentController.java
ClientSide/src/main/java/Client/updateNotes.java
ClientSide/src/main/resources/Client/showStudentTest.fxml
ClientSide/src/main/resources/Client/showStudentTests.fxml

Server doesn't get correct values - should check why

Exam Notes for Teacher grade approve

---

ClientSide/src/main/java/Client/ClientService.java
ClientSide/src/main/java/Client/showStudentTest.java
ClientSide/src/main/java/Client/showStudentTests.java
ClientSide/src/main/java/Client/testEntracnce.java
ClientSide/src/main/resources/Client/showStudentTest.fxml
Common/src/main/java/UtilClasses/updateNotes.java
ServerSide/src/main/java/Controllers/DoTestController.java
ServerSide/src/main/java/Server/ServerMain.java

Teacher now can add comments and approve grades for student's test,
works with no problems (finally..)

Notes to StudentTest + manual test approve is better
